/** todos los menús */
export const MENUDATA = [
  {
    id: 4,
    discount: "63 MIL",
    img: "/assets/item4.webp",
    title: "CHICKEN SHARE",
    details: ["6 piezas", "en combo"],
    price: ["93 MIL", "GS."],
  },
  {
    id: 5,
    discount: null,
    img: "/assets/item5.webp",
    title: "MEGA RECARGADOS",
    details: ["8 piezas", "2 sand. Cheddar", "2 papas medianas"],
    price: ["147 MIL", "GS."],
    nota: "PARA 6 PERSONAS",
  },
  {
    id: 1,
    discount: null,
    img: "/assets/item1.webp",
    title: "BUCKETS",
    details: ["8 PIEZAS"],
    price: ["85 MIL", "GS."],
    nota: "PARA 3 A 4 PERSONAS",
  },
  {
    id: 6,
    discount: null,
    img: "/assets/item6.webp",
    title: "MEGA FAMILIAR",
    details: ["8 piezas", "4 alitas", "5 strips"],
    price: ["147 MIL", "GS."],
    nota: "PARA 4 PERSONAS",
  },
  {
    id: 7,
    discount: null,
    img: "/assets/item7.webp",
    title: "MEGA XL",
    details: ["8 piezas", "8 strips", "8 alitas", "2 papas medianas"],
    price: ["147 MIL", "GS."],
    nota: "PARA 5 PERSONAS",
  },
  {
    id: 2,
    discount: null,
    img: "/assets/item2.webp",
    title: "BIG BOX FULL",
    details: [
      "1 pieza",
      "2 strips",
      "2 alitas",
      "1 acomp. peq.",
      "1 gaseosa 250 cc",
    ],
    price: ["46 MIL", "GS."],
  },
  {
    id: 3,
    discount: null,
    img: "/assets/item3.webp",
    title: "BIG BOX KENTUCKY",
    details: [
      "1 kentucky chicken",
      "3 alitas",
      "1 pure peq.",
      "1 gaseosa 250 cc",
    ],
    price: ["46 MIL", "GS."],
  },
];
